blog/urls.py
from django.urls import path, re_path
from .views import ArticleList, ArticleDetail, CategoryList, AuthorList, ArticlePreview

app_name = "blog"

urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('page/<int:page>', ArticleList.as_view(), name="home"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
    path('article/<int:spk>', ArticlePreview.as_view(), name="preview"),
    path('category/<slug:slug>', CategoryList.as_view() , name="category"),
    path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
    path('category/<slug:username>', AuthorList.as_view() , name="author"),
    path('category/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Logout, register, verify
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name= 'login'),
    path('logout/', Logout.as_view(), name= 'logout'),
    path('register/', register, name= 'register'),
    path('verify/', verify, name='verify'),
    # re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) 

blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils.html import format_html
from django.utils import timezone
from extensions.utils import jalali_converter
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment

# my manager
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status= 'p')
class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status= True)

# Create your models here.
class Category(models.Model):
    parents = models.ForeignKey('self', default= None, null= True, blank= True, on_delete= models.SET_NULL, related_name= 'children', verbose_name="زیر دسته")
    title = models.CharField(max_length= 200, verbose_name ="عنوان دسته بندی")
    slug = models.SlugField(max_length= 100, unique= True, verbose_name ="آدرس دسته بندی")
    status = models.BooleanField(default= True, verbose_name="آیا نمایش داده شود")
    position = models.IntegerField(verbose_name= "پوزیشن")

    # class Meta():
    #     verbose_name = "دسته بندی"
    #     verbose_name_plural = "دسته بندی ها"
    #     oedering = ['parent','position']

    def __str__(self):
        return self.title

    objects = CategoryManager()    


class Article(models.Model):
    STATUS_CHOICES = {
        ('d', 'پیش نویس'),
        ('p', 'منتتشر شده'),
        ('i', 'در حال بررسی'),
        ('b', 'برگشت داده شده'),
    }
    author = models.ForeignKey(User, null=True, on_delete= models.SET_NULL, related_name='articles', verbose_name= 'نویسنده')
    title = models.CharField(max_length= 200, verbose_name ="عنوان مقاله")
    slug = models.SlugField(max_length= 100, unique= True, verbose_name ="آدرس مقاله")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name='articles')
    description = models.TextField(verbose_name ="محتوا")
    thumnale = models.ImageField(upload_to= "images", verbose_name ="تصویر مقاله")
    publish = models.DateTimeField(default= timezone.now, verbose_name ="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name ="")
    is_special = models.BooleanField(default= False, verbose_name="مقاله ویژه")
    status = models.CharField(max_length= 1, choices=STATUS_CHOICES, verbose_name ="وضعیت")
    comments = GenericRelation(Comment)

    # class Meta():
    #     verbose_name = "مقاله"
    #     verbose_nameـplural = "مقالات"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:home")
    
    def jpublish(self):
        return jalali_converter(self.publish)

    jpublish.short_description = "زمان امروز"

    # def category_published(self):
    #     return self.category.filter(status = True)
    
    def thumbnail_tag(self):
        return format_html("<img width=100 height= 75 style= 'border-radius: 5px' src='{}'>".format(self.thumnale.url))
    thumbnail_tag.short_description = "عکس"
    
    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = "دسته بندی"
    
    objects = ArticleManager()

blog/views.py
from typing import Any
from account.models import User
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from account.mixins import AuthorAccessMixin
# from django.http import HttpResponse, JsonResponse
from .models import Article, Category

# Create your views here.
def home(request, page =1):
    article_list = Article.objects.published()
    paginator = Paginator(article_list, 6)
    articles = paginator.get_page(page)
    context = {
        "articles" : articles,
        "category" : Category.objects.filter(status= True)
    }
    return render(request, "blog/home.html", context)
class ArticleList(ListView):
    queryset = Article.objects.published()
    paginate_by = 6
    

# def detail(request, slug):
#     context = {
#         "article": get_object_or_404(Article.objects.published(), slug=slug),
#         "category" : Category.objects.filter(status= True)
#     }
#     return render(request, "blog/detail.html", context)
class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)
#     return render(request, "blog/detail.html", context)

class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk =pk)


# def category(request, slug, page=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     article_list = category.articles.published()
#     paginator = Paginator(article_list, 6)
#     articles = paginator.get_page(page)
#     context = {
#         "category": category,
#         "article" : articles
#     }
#     return render(request, "blog/category.html", context)
class CategoryList(ListView):
    paginate_by = 6
    template_name = 'blog/category_list.html'

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    paginate_by = 6
    template_name = 'blog/auther_list.html'

    def get_queryset(self):
        global author
        username = self.kwargs.get('slug')
        author = get_object_or_404(User.objects.active(), username=username)
        return author.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %}

{% load static %}

{% block title %} {{object.title}} {% endblock %}

{% block main %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{{object.thumnale.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1 class="text-center" style="font-family: B Yekan;">{{object.title|safe}}</h1>
                    {% if article.is_special %}
                        <span class="badge badge-danger" style="font-size: 14px; font-family: Sahel;">ویژه</span>
                    {% endif %}
                    
                    <time style="font-family: Sahel;">{{object.jpublish}}</time>
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container">
        <div class="row gx-4 gx-lg-5 justify-content-center">

            <div class="col-md-10 col-lg-8 col-xl-7 text-justify" style="font-family: Sahel;">
                {% if object.is_special %}
                    {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser%}
                        {{object.description|safe}}
                    {% else %}
                        {{article.description|striptags|truncatewords:30}}
                        <p class="alert alert-warning">این مقاله ویژه است و برای مشاهده کامل آن باید <a class="alert-link" href="#">اشتراک ویژه</a> تهیه کنید.</p>
                    {% endif %}
                {% else %}
                    {{object.description|safe}}
                {% endif %}

                {% render_comments object request %}
                {% include_static %}
                {% include_bootstrap %}
                
            </div>
            
        </div>
    </div>
</article>

{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}{% endblock %}

{% block pervious_page_url %}
    {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/auther_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center"> نویسنده: {{author.get_full_name}}</h3>
{% endblock %}

{% block pervious_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html dir="rtl">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog {% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static '/blog/css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar-nav navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            {% block category_navbar %}{% endblock %}
            <div class="collapse navbar-collapse" id="navbarResponsive" style="font-family: vazir;">
                <ul class="navbar-nav my-3 py-4 py-lg-0">
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 my-3 py-3 py-lg-4" style="font-size: 14px;" href="{% url 'blog:home' %}">خانه</a>
                    </li>
                    <li class="nav-item">
                        <div class="dropdown dropdown-toggle nav-link px-lg-3 py-3 py-lg-4" style="font-family: vazir;">
                            <button class="btn" type="button" data-bs-toggle="dropdown" style="font-family: vazir;">
                                دسته بندی ها
                            </button>
                            <ul class="dropdown-menu" style="background-color: transparent;">
                                {% for cat in category_list %}
                                    <li><a class="dropdown-item" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Content-->
    {% block main %}
    {% endblock %}
    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a target="_blank" href="https://github.com/amrayi/django_project">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'blog/js/scripts.js' %}"></script>
</body>

</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center" style="font-family: sahel;">دسته بندی: {{category.title}}</h3>
{% endblock %}

{% block pervious_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}


<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1 style="font-family: B Yekan ;">امیر محمد امرایی</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Navigation-->
<nav class="navbar-nav navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
            </ul>
        </div>
    </div>
</nav>
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->

            {% block header %}{% endblock %}
            
            {% for article in object_list %}
            <div class="post-preview">

                <a href="{% url 'blog:detail' article.slug %}">
                    <h2 class="post-title" style="font-family: B Yekan;">
                        {{article.title}}
                        {% if article.is_special %}
                            <span class="badge badge-danger" style="font-size: 14px;">ویژه</span>
                        {% endif %}
                    </h2>
                    <h3 class="post-subtitle" style="font-family: sahel; font-size: 18px;">{{article.description|striptags|truncatewords:30}}</h3>
                </a>
                <p class="post-meta" style="font-family: sahel;">
                    نوشته شده توسط
                    <a href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>
                    {{article.jpublish}}
                </p>
                {% for cat in article.category.active %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
            </div>
            <hr class="my-4" />
            {% endfor %}

            <!-- pager-->
            {% if is_paginated %}
            <div class="d-flex justify-content-end mb-4">
                {% if page_obj.has_previous %}
                <a class="btn btn-primary text-uppercase ml-3"
                    href="{% block pervious_page_url %}{% endblock %}" style="font-family: B Yekan;">پست های جدید →</a>
                {% endif %}
                {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase" href="{% block next_page_url %}{% endblock %}" style="font-family: B Yekan;">
                    پست های قدیم →</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
</div>

{% endblock %}